[package]
name = "laz"
version = "0.1.0"
authors = ["tmontaigu <thomas.montaigu@laposte.net>"]
edition = "2018"
license-file = "COPYING"
exclude = [
    "tests/data",
]

[profile.release]
debug = true

[dependencies]
num-traits = "0.2.8"
byteorder = "1.3.1"


