name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Build with parallel
      run: cargo build --features parallel --verbose
    - name: Run tests with parallel
      run: cargo test --features parallel --verbose
